version: build-{build}-{branch}
environment:
  TF_ACC: 1
  POWERBI_TENANT_ID:
    secure: 6hS9YiKUSupL9ZlzhgkVsCoSMUmHZXZkqJkH89itiBRcGdFZ5x0Kp7bevVaqDCcc
  POWERBI_CLIENT_ID:
    secure: 0B4c4WBNdUBtH18ckJVGN0hEwvIpCxdJOo+vhVWSW+gxWIUUCdH0+vyYp0CyJ/Eb
  POWERBI_CLIENT_SECRET:
    secure: asAqoO5uam6uLKftR+vyjtHMlCgyok0GsDvQLr6APa/GecN/w4SqGcPkUa41WgHP
  POWERBI_USERNAME:
    secure: l4QpQQoZv7NnLSEyzKwLzSZFMQRkWOFpd/Yfp1RqwXMgEbl4LyN7DXDZjvzCr5+e
  POWERBI_PASSWORD:
    secure: 5z0At8R96g/HOEEvlJVjcw==
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    GOOS: linux
    GOARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GOOS: windows
    GOARCH: amd64
build_script:
- pwsh: |
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      Write-Host "Building release from tag '$($env:APPVEYOR_REPO_TAG_NAME)'"
      Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME
      $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_REPO_TAG_NAME
    }
    
    $dir = "$($env:GOOS)_$($env:GOARCH)"
    $outputPath = "bin/$dir/terraform-provider-powerbi_$($env:APPVEYOR_BUILD_VERSION)"
    if ($($env:GOOS) -eq "windows") { $outputPath += ".exe" }
    
    Write-Host "Building '$outputPath'"
    go build -o $outputPath

    Write-Host "Zip folder 'bin/$dir' to 'bin/$dir.zip'"
    Compress-Archive -Path "bin/$dir" -DestinationPath "bin/$dir.zip"
    
    $artifactFilename = "$($dir)_terraform-provider-powerbi_$($env:APPVEYOR_BUILD_VERSION).zip"
    Push-AppveyorArtifact bin/$dir.zip -FileName $artifactFilename -DeploymentName 'terraform-provider-powerbi'
test_script:
- pwsh: |
    go test -v ./...
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: VpsAsWfet05ak8vyY7x1N9QcXXidnkXCiUvRn+xdZKLK89wWIDj3Yg5bzF/47dDb
  artifact: terraform-provider-powerbi
  draft: false
  prerelease: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true