name: Release
on:
  release:
    types: [published]

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.6

      - name: Get Version
        id: version
        run: |
          echo "version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_OUTPUT

      - name: Prepare Go
        run: |
          go mod tidy
          go mod download
          go mod verify
          go mod vendor

      - name: Build Artifacts
        run: |
          make build-all VERSION=${{ steps.version.outputs.version }}

      - name: Rename Artifacts
        run: |
          for arch in darwin_arm64 linux_amd64 windows_amd64; do
            version=${{ steps.version.outputs.version }}
            mv bin/${version}/${arch}/terraform-provider-powerbi_v${version} bin/${arch}-v${version}
          done

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            bin/darwin_arm64-v${{ steps.version.outputs.version }}
            bin/linux_amd64-v${{ steps.version.outputs.version }}
            bin/windows_amd64-v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
